# Generated by Django 4.0.8 on 2023-05-21 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_userinfo_delete_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='user',
            new_name='userFK',
        ),
    ]
