# Generated by Django 4.0.8 on 2023-05-21 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_user_userinfo_userfk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='userFK',
            new_name='user',
        ),
    ]
