# Generated by Django 4.0.8 on 2023-05-31 15:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_post_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post_comment',
            new_name='PostComment',
        ),
    ]
